= Acknowledgment (Agradecimentos)
:author: Paulo Jerônimo
:email: pj@paulojeronimo.info

== English version

TODO

== Versão em português

Ao criar essa apresentação estou consolidando e aprimorando algum conhecimento que adquiri ao longo dos últimos anos. O que aprendi foi obtido através do estudo de documentos e projetos produzidos por algumas pessoas que fizeram, e fazem a diferença em minha vida, enquanto desenvolvedor e/ou escritor. Essas pessoas talvez não saibam de sua importância para mim mas, mesmo assim, quero agradeçe-las. Preciso deixar, aqui, o meu reconhecimento pelo seu trabalho. Especificamente, para esse projeto, eu gostaria de agradecer a https://twitter.com/mojavelinux[Dan Allen], https://twitter.com/arungupta[Arun Gupta], https://twitter.com/aslakknutsen[Aslak Knutsen], https://twitter.com/emmanuelbernard[Emmanuel Bernard], http://twitter.com/mgreau[Maxime Gréau], e https://github.com/edusantana[Eduardo Santana].

Agradeço ao Dan Allen pelos muitos documentos e apresentações que ele produziu relativos ao AsciiDoc, ao Asciidoctor e ao Awestruct. Meu primeiro contato com o AsciiDoc surgiu quando ele publicou o documento http://mojavelinux.github.io/asciidoc-examples/javaeeworkshop.html["JBoss Java EE 6 Workshop"], em 2012. Nessa época, eu pude aprender muito, não somente sobre o Java EE 6 no JBoss, como também sobre o OpenShift e sobre o AsciiDoc. Contudo, eu ainda estava muito envolvido com o http://txt2tags.org[Txt2tags], uma ferramenta fantástica do http://aurelio.net[Aurélio Jargas], e continuei a escrever meus documentos com ela. Ainda hoje, gosto e utilizo muito essa ferramenta. Mas, ao reiniciar a escrita de meu livro sobre o JBoss, eu comecei a dar mais valor ao AsciiDoc que no início. Eu https://leanpub.com/jbcaa[comecei a escrevê-lo] utilizando a infraestrutura provida pelo LeanPub, que usa minha conta no Dropbox e o formato Markdown. Algum tempo depois, ministrei um treinamento de Java EE. Um dos projetos que falei foi o http://www.jboss.org/jdf/examples/ticket-monster/tutorial/Introduction/[Ticket Monster], onde parte da documentação tinha sido escrita pelo Dan Allen (e outros autores). Percebi, ao observar como o Ticket Moster havia sido documentado, utilizando o AsciiDoc, que seu modelo seria tudo o que eu precisaria para continuar a escrita do meu livro, sem a necessidade do LeanPub. Então, comecei a migrá-lo de Markdown para AsciiDoc. Também agradeço ao Dan, pelo fato de que essa apresentação só foi possível por eu ter conseguido realizar, com sucesso, a execução de seu workshop http://mojavelinux.github.io/decks/docs-workshop/rwx2013/index.html["Easier Documentation, Simpler Websites & Faster Collaboration"].

Antes do evento JBoss in Bossa, em São Paulo/2010, http://a.ladoservidor.com/tutoriais/arquillian-shrinkwrap/index.html[eu escrevi um tutorial sobre Arquillian e ShrinkWrap]. Algum tempo após, com o produto já mais maduro e com um site bem acabado, percebi que o desenvolvimento do site do Arquillian havia sido realizado com o Awestruct. Então, comecei a ter maior interesse por esse último. Creio que o trabalho de Aslak Knutsen no site do Arquillian tenha uma boa influência no fato de eu querer utilizar o Awestruct. Então, fica aqui o meu agradecimento a ele.

Outras pessoas pessoas que também me influenciaram, indiretamente, a iniciar o desenvolvimento de um site pessoal (atualmente só mantenho um blog muito simples), foram Emmanuel Bernard e Maxime Gréau. Com seus sites escritos com um design simples e funcional, utilizando o Awestruct, eles chamaram a minha atenção de tal forma que eu decidi fazer um clone de seus sites do GitHub para estudá-los a fim de começar a escrever meu. Pelo que li, ambos moram na França. Eu gostaria de ter a oportunidade de conhecê-los, e agradecer-lhes pessoalmente durante um encontro, quando eu visitar seu país no final de junho para participar do http://eu.ironman.com/triathlon/events/emea/ironman/france.aspx[Ironman em Nice].

Arun Gupta é uma pessoa com quem mantenho contatos exporádicos desde sua vinda ao Brasil em junho de 2011. Na época, tivemos a oportunidade de fazer uma https://blogs.oracle.com/arungupta/entry/brasilia_community_run_powered_by[corrida de 10 Km em Brasília] e, na mesma semana, conversar numa viagem de carro até Goiânia. Em seguida, também pude ajudá-lo em alguns trabalhos. Especificamente com relação ao meu trabalho nessa apresentação, o projeto wildfly-deck do Arun foi útil. Ele me poupou algum tempo em configurações que eu queria fazer relativas ao dzslides e ao asciidoctor-backends. Além disso, as poucas dicas escritas nesse projeto relativas a instalação do deck2pdf, foram suficientes para que eu conseguisse configurá-lo em meu ambiente. Obrigado, Arun!

Finalmente, agradeço ao Eduardo Santana. Apesar dele morar aqui no Brasil, eu não o conheço pessoalmente e, até esse momento, não trocamos nenhuma mensagem, embora eu desejasse ter feito isso a algum tempo atrás. Contudo, o trabalho que Eduardo publicou em seu GitHub, relativo a projeto de publicações de livros da UFPB, tem sido útil para mim. Fiz algumas adaptações ao seu projeto (espero devolvê-las em forma de contribuição em breve) e comecei a utilizá-lo em meu próprio ambiente, junto com suas configurações de AsciiDoc, para escrever o meu livro de JBoss. E, por falar nesse livro, eu tenho o intuito de acabá-lo nesse semestre. Diversas outras prioridades tomaram conta do meu tempo nesses últimos meses mas, mesmo assim, estou buscando tempo para escrever.
