= Guia, passo a passo
:author: Paulo Jerônimo
:email: pj@paulojeronimo.info
:toc:
:numbered:

== Instalando a VM

=== Baixando e extraindo a VM
[source,bash]
----
$ cd ~/VirtualBox VMs/
$ bash <(curl -L http://j.mp/vm-fedora-download)
$ 7z x vm-fedora.7z.001
----

=== Registrando a VM no VirtualBox
[source,bash]
----
$ VBoxManage registervm "$PWD/vm-fedora/vm-fedora.vbox"
----

=== Gerando um snapshot de pós-instalação
[source,bash]
----
$ VBoxManage snapshot vm-fedora take fedora-pos-install
----

== Executando e configurando a VM

=== Iniciando a VM
[source,bash]
----
$ VBoxManage startvm vm-fedora
----

=== Efetuando o logon
* Usuário: aluno
* Senha: @lun0123

=== Configurando teclado e proxy
[source,bash]
----
$ sudo loadkeys br-abnt2
$ bash <(curl -L http://j.mp/fedora-proxy-config)
$ logout
----

=== Visualizando o passo a passo pelo tmux
[source,bash]
----
$ bash <(curl -L http://j.mp/jc-tmux-view)
----

=== Configurando algumas variávies de ambiente
[source,bash]
----
$ f=~/ambiente; cat > $f <<EOF
export PROJECT=join-community
export PROJECT_NAME="Join Community"
export PROJECT_TITLE="$PROJECT_NAME - Boas práticas em arquitetura e desenvolvimento de software"
export BASE_USER=pj
export GITHUB_USER=paulojeronimo
export GITHUB_NAME='Paulo Jerônimo'
export GITHUB_EMAIL=pj@paulojeronimo.info
export TREE_CHARSET=ASCII
export PS1='\$ '
EOF
$ vim $f
----

=== Carregando o ambiente na inicialização do shell
[source,bash]
----
$ grep `basename $f` ~/.bashrc &> /dev/null || \
echo "[ -f $f ] && source $f" >> ~/.bashrc
$ source $f
----

== RVM & Ruby

=== Instalando o Ruby 1.9.3, via RVM em modo single-user
[source,bash]
----
$ curl -sSL https://get.rvm.io | bash -s stable
$ source ~/.rvm/scripts/rvm
$ type rvm | head -n 1
$ which rvm
$ rvm list known | less
$ rvm list known | grep 1.9
$ rvm install 1.9.3
$ ruby -v
----

=== Refazendo o logon para verificar se o Ruby ainda funciona
[source,bash]
----
$ tmux kill-session
$ logout
# Refaça o logon
$ !?tmux-view
$ ruby -v
----

=== Removendo a instalação, realizada em modo single-user, do RVM
[source,bash]
----
$ rm -rf ~/.rvm
$ sed -i '/rvm/d' ~/.bash_profile
$ sed -i '/rvm/d' ~/.bashrc
$ rm ~/.profile
$ !?kill-session
$ logout
# Refaça o logon
$ !?tmux-view
----

=== Verificando se o RVM e o Ruby foram removidos
[source,bash]
----
$ rvm list known # deverá apresentar 'command nout found'
$ ruby -v # deverá apresentar 'command nout found'
----

=== Instalando o Ruby 1.9.3, via RVM em modo multi-user
[source,bash]
----
$ curl -sSL https://get.rvm.io | sudo -E bash -s stable
$ sudo useradd -G wheel,rvm -m -s /bin/bash rvmuser
$ sudo su - rvmuser
$ type rvm | head -n 1
$ which rvm
$ rvm list known | grep 1.9
$ rvm install 1.9.3
$ ruby -v
$ logout
$ sudo userdel -rf rvmuser
$ sudo gpasswd -a $USER rvm
$ !?kill-session
$ logout
----

=== Instalando o Ruby 2.1.1, via RVM em modo multi-user, e tornando-o a versão default
[source,bash]
----
# Refaça o logon
$ !?tmux-view
$ !?type
$ which rvm
$ ruby -v
$ rvm install 2.1.1
$ !-2
$ rvm list
$ rvm use 2.1.1 --default
$ !-2
$ ruby -v
----

=== Removendo o Ruby 1.9.3, via RVM
[source,bash]
----
$ rvm remove 1.9.3
# Deverá dar erro! :/
# O usuário aluno não tem privilégios para remover o diretório (criado por rvmuser)
# Solução de contorno: fazer a remoção manual, como root:
$ sudo rm -rf /usr/local/rvm/rubies/ruby-1.9.3-p545/
$ rvm list
----

== Awestruct & Asciidoctor

=== Instalando o Awestruct
[source,bash]
----
$ rvm use 2.1.1@$PROJECT --create
$ sudo yum -y install libxml2-devel libxslt-devel
$ gem install tilt --version 1.4.1
$ gem install awestruct --version 0.5.4.rc3
$ gem install asciidoctor
----

=== Criando um novo projeto com o Awestruct
[source,bash]
----
$ mkdir $PROJECT
$ cd !$
$ awestruct -i -f foundation
----

=== Configurando um Gemfile
[source,bash]
----
$ cat > Gemfile << LINES
source 'https://rubygems.org'
gem 'awestruct', '0.5.4.rc3'
gem 'asciidoctor', '0.1.4'
gem 'tilt', '1.4.1'
gem 'rake', '>= 0.9.2'
gem 'git', '1.2.6'
LINES
----

=== Fazendo o lock das dependências
[source,bash]
----
$ gem install bundler
$ bundle install
----

=== Vendo a estrutura do projeto
[source,bash]
----
$ tree | less
----

=== Gerando o site
[source,bash]
----
$ rake
----

=== Criando um túnel reverso para ver o site gerado a partir da máquina base
* Digite <Ctrl b c>, na console do tmux, para abrir uma nova janela. Em seguida, execute:
[source,bash]
----
$ ssh -R 4242:localhost:4242 $BASE_USER@base
----
* Abra seu browser na máquina base no endereço http://localhost:4242

=== Observando a estrutura do site gerado
* Volte para a janela que está executando o awestruct via rake (<Ctrl b n>). Dê um <Ctrl c> no servidor. Em seguida, execute:
[source,bash]
----
$ tree _site/ | less
----

=== Configurando o Git
[source,bash]
----
$ git config --global user.email "$GITHUB_EMAIL"
$ git config --global user.name "$GITHUB_NAME"
$ cat ~/.gitconfig
----

=== Configurando um repositório Git para o projeto
[source,bash]
----
$ git init .
----

=== Instruindo o Git a ignorar arquivos gerados
[source,bash]
----
$ cat > .gitignore << LINES
/.awestruct/
/.ruby-*
/.sass-cache/
/_site/
/_tmp/
/Gemfile.lock
LINES
----

=== Desabilitando o Jekyll
[source,bash]
----
$ touch .nojekyll
----

=== Adicionando os arquivos não ignorados e fazendo o primeiro commit
[source,bash]
----
$ git add .
$ git commit -m 'commit inicial'
----

=== Criando um repositório remoto no GitHub

=== Publicando seu repositório local no GitHub
[source,bash]
----
$ git remote add origin https://github.com/$GITHUB_USER/$PROJECT
$ git push origin master
----

=== Configurando a identidade do site
[source,bash]
----
$ cat > _config/site.yml <<EOF
name: $PROJECT_NAME
title: $PROJECT_TITLE
org: $GITHUB_NAME
author: $GITHUB_USER
author_url: https://github.com/$GITHUB_USER
base_url: ''
ctx_path: ''
EOF
$ cat _config/site.yml
----

=== Adicionando configurações para configurar o processador
[source,bash]
----
$ cat >> _config/site.yml <<EOF
interpolate: false
haml:
  :ugly: true
EOF
----

=== Limpando e regerando o site para ver as mudanças
[source,bash]
----
$ rake clean preview
----

=== Configurando o uso do AsciiDoctor
[source,bash]
----
$ cat >> _config/site.yml <<EOF
asciidoctor:
  :safe: safe
  :attributes:
    sitename: $PROJECT_NAME
    base_url: ''
    ctx_path: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font
EOF
----
