= Criação e disponibilização de uma máquina virtual Fedora 20
:author: Paulo Jerônimo
:email: pj@paulojeronimo.info
:toc:
:numbered:

== Preparando o ambiente Fedora para criar e disponibilizar a VM
=== Instalando alguns utilitários
[source,bash]
----
$ sudo yum -y install \
vim-enhanced \
p7zip
----

=== Instalando o Apache
* Passo a passo em http://a.paulojeronimo.info/tutoriais/fedora-mac/index.html#toc30

=== Instalando o VirtualBox
* Passo a passo em http://a.paulojeronimo.info/tutoriais/fedora-mac/index.html#toc31

=== Instalando um cliente para o Google Drive
* TODO

=== Configurando variáveis de ambiente
[source,bash]
----
$ f=~/join-community-2014.conf; cat > $f <<'EOF'
# diretório dos mirrors
MIRRORS_DIR=/data/mirrors

# diretório do mirror do Fedora
FEDORA_MIRROR=$MIRRORS_DIR/Fedora-20-x86_64

# diretório de download de arquivos desse passo a passo
DOWNLOADS_DIR=~/join-community-2014.downloads

# diretório de configurações do Apache
APACHE_CONF_DIR=/etc/httpd/conf.d

# comando para fazer o reload das configurações do Apache
APACHE_RELOAD_CMD="systemctl reload httpd"

# localização do ISO de instalação do Fedora
export FEDORA_ISO=$FEDORA_MIRROR/releases/20/Fedora/x86_64/iso/Fedora-20-x86_64-netinst.iso
EOF
$ vim $f
$ grep `basename $f` ~/.bashrc &> /dev/null || \
echo "[ -f $f ] && source $f"  >> ~/.bashrc
$ source $f
----

== Criando a VM
=== Configurando o uso de um mirror local do Fedora 20
[source,bash]
----
$ mkdir -p $DOWNLOADS_DIR
$ cd !$
$ git clone http://github.com/paulojeronimo/mirrors.git
$ cd mirrors
$ cat > .bin/config <<EOF
LOCAL_MIRRORS_DIR_ON_LINUX=$MIRRORS_DIR
EOF
$ .bin/create-links
----

=== Criando e/ou atualizando o mirror local
[source,bash]
----
$ sudo Fedora/20/x86_64/mirror.sh
----

=== Configurando o Apache
[source,bash]
----
$ cd $DOWNLOADS_DIR
$ git clone https://github.com/paulojeronimo/join-community-2014.git
$ ./join-community-2014/configurar-apache.sh
----

=== Criando, iniciando e instalando o Fedora 20 na VM
[source,bash]
----
$ ./mirrors/Fedora/20/x86_64/vm/vbox
$ VBoxManage startvm vm-fedora
----
[NOTE]
======
No boot da VM, pressione <Tab> e adicione +ks=http://10.0.2.2/ks+ ao final da linha de comando.
======

=== Entendo o processo de instalação automática do Fedora
[source,bash]
----
$ vim join-community-2014/vm/ks
----

=== Fazendo o shutdown após a instalação e removendo o "DVD" do Fedora do drive
[source,bash]
----
$ VBoxManage controlvm vm-fedora acpipowerbutton
$ VBoxManage storageattach vm-fedora \
--storagectl "IDE Controller" \
--port 1 --device 0 --type dvddrive --medium emptydrive
----

=== Reiniciando a VM e removendo arquivos desnecessários
[source,bash]
----
$ VBoxManage startvm vm-fedora
----

* Logue-se na VM (usuário/senha: aluno/@lun00123) e execute:
[source,bash]
----
$ sudo package-cleanup -y --oldkernels --count=1
$ d=/var/cache/yum/; sudo bash -c "rm -rf $d; mkdir -p $d"
$ history -c
----

=== Desligando e reconfigurando os drives de CD/DVD da VM
[source,bash]
----
$ VBoxManage controlvm vm-fedora acpipowerbutton
$ VBoxManage storagectl vm-fedora \ 
--name "IDE Controller" --remove
$ VBoxManage storagectl vm-fedora \
--name "IDE Controller" --add ide --controller PIIX4
$ VBoxManage storageattach vm-fedora \
--storagectl "IDE Controller" \
--port 1 --device 0 --type dvddrive --medium emptydrive
----

=== Desregistrando a VM
[source,bash]
----
$ VBoxManage unregistervm vm-fedora
----

== Disponibilizando a VM para download
=== Limpando arquivos desnecessários e compactando a VM
[source,bash]
----
$ cd ~/VirtualBox\ VMs
$ (cd vm-fedora && \
find . ! \( -name . -o -name vm-fedora.vbox -o -name vm-fedora.vdi \) | \
xargs rm -rf)
$ 7za a -mmt -v200m vm-fedora vm-fedora/
$ sha1sum vm-fedora.7z.* > vm-fedora.sha1sum
----
=== Gerando o script para o download da VM
[source,bash]
----
$ f=vm-fedora.download.sh; sed "s/COUNT/`ls vm-fedora.7z.* | wc -l`/g" \
$DOWNLOADS_DIR/join-community-2014/vm/$f > $f
----

=== Fazendo upload para o Google Drive
* Montando o Google Drive:
[source,bash]
----
$ mkdir ~/google-drive
$ google-drive-ocamlfuse ~/google-drive
----
* Fazendo a cópia da VM:
[source,bash]
----
$ rsync -av vm-fedora.* ~/google-drive/vm-fedora/
----
* Desmontando o Google Drive:
[source,bash]
-----
$ fusermount -u ~/google-drive
-----
* Terminado o upload, os arquivos ficam disponíveis em http://gdriv.es/vm-fedora/. Essa é uma URL curta, que criei no http://gdriv.es, para a URL longa https://drive.google.com/folderview?id=0B_tTlCk55SmjZGlNckhCRldUUDQ.

== Para reiniciar esse passo a passo
[source,bash]
----
$ sudo rm -rf /etc/httpd/conf.d/join-community-2014.conf 
$ sudo systemctl reload httpd
$ rm -rf join-community-2014.*
$ VBoxManage unregistervm vm-fedora --delete
$ rm -rf ~/VirtualBox\ VMs/vm-fedora.7z.*
$ sed -i '/join-community/d' ~/.bashrc
----
