= Guia, passo a passo
:author: Paulo Jerônimo
:email: pj@paulojeronimo.info
:toc:
:toclevels: 3
:numbered:
:experimental:

== Instalando a VM

=== Baixando e extraindo a VM
[source,bash]
----
$ cd ~/VirtualBox\ VMs/
$ bash <(curl -L http://j.mp/vm-fedora-download)
$ 7za x vm-fedora.7z.001
----

=== Registrando a VM no VirtualBox
[source,bash]
----
$ VBoxManage registervm "$PWD/vm-fedora/vm-fedora.vbox"
----

=== Gerando um snapshot de pós-instalação
[source,bash]
----
$ VBoxManage snapshot vm-fedora take fedora-pos-install
----

== Executando e configurando a VM

=== Iniciando a VM
[source,bash]
----
$ VBoxManage startvm vm-fedora
----

=== Efetuando o login no console da VM
* Usuário: aluno
* Senha: @lun0123

=== Executando algumas configurações opcionais
==== Configurando teclado e proxy
* Configure o teclado, se necessário:
[source,bash]
----
$ sudo loadkeys br-abnt2
----
* O comando acima altera o teclado somente enquanto a VM está em execução. Se quiser deixar o teclado br-abnt2 configurado de forma permanente, execute:
[source,bash]
----
$ sudo localectl set-keymap br-abnt2
----
* Se estiver acessando a Internet através de um proxy, execute:
[source,bash]
----
$ configurar-proxy.sh
----
* Se configurou o proxy, faça o logout pois as suas configurações só serão visíveis após um novo login:
[source,bash]
----
$ logout
----

==== Utilizando o seu mirror local ao invés dos remotos
* Refaça o login pelo console da VM e execute:
[source,bash]
----
$ for repo in fedora updates; \
do sudo yum-config-manager --disable $repo; done
$ sudo yum-config-manager --enable local-mirror-\*
----

=== Atualizando a lista de pacotes da VM
[source,bash]
----
$ sudo yum -y update
----

=== Instalando os pacotes básicos necessários para esse tutorial
==== Instalando vim, tree, lynx, tmux, tar, ...
[source,bash]
----
$ sudo yum -y install \
vim-enhanced \
tree \
lynx \
tmux \
tar
----
=== Visualizando o passo a passo pelo tmux
[source,bash]
----
$ bash <(curl -L http://j.mp/jc-tmux-view)
----

=== Configurando algumas variávies de ambiente
[source,bash]
----
$ f=~/ambiente; cat > $f <<'EOF'
export PROJECT=join-community
export PROJECT_NAME='Join Community'
export PROJECT_TITLE='Join Community - Boas práticas em arquitetura e desenvolvimento de software'
export BASE_USER=pj
export GITHUB_USER=paulojeronimo
export GITHUB_NAME='Paulo Jerônimo'
export GITHUB_EMAIL=pj@paulojeronimo.info
export TREE_CHARSET=ASCII
export PS1='\$ '
EOF
$ vim $f
----

=== Carregando o ambiente na inicialização do shell
[source,bash]
----
$ grep `basename $f` ~/.bashrc &> /dev/null || \
echo "[ -f $f ] && source $f" >> ~/.bashrc
$ cat ~/.bashrc
$ source $f
----

=== Acessando a VM a partir da base
[source,bash]
----
$ ssh-keygen
$ ssh-copy-id $BASE_USER@base
$ ssh $BASE_USER@base
$ logout
$ echo 'while true; do sleep 1; done' | \
nohup ssh -R 2222:localhost:22 $BASE_USER@base bash &
$ tmux kill-session
$ logout
----
.autossh
[NOTE]
======
Mais a frente utilizaremos o comando +autossh+ para melhorar isso ...
======
* Na base, se ainda não tiver gerado suas chaves, execute:
[source,bash]
----
$ ssh-keygen
----
* Em seguida, exporte sua chave pública para a VM:
[source,bash]
----
$ ssh-copy-id -p 2222 aluno@localhost
$ ssh -p 2222 !$
$ !?tmux-view
----

== Instalando o Ruby via RVM

=== Instalando o Ruby 1.9.3, via RVM em modo single-user
[source,bash]
----
$ curl -sSL https://get.rvm.io | bash -s stable
$ source ~/.rvm/scripts/rvm
$ type rvm | head -n 1
$ which rvm
$ rvm list known | less
$ rvm list known | grep 1.9
$ rvm install 1.9.3
$ ruby -v
----

=== Refazendo o logon para verificar se o Ruby ainda funciona
[source,bash]
----
$ !?kill-session
$ logout
$ !?ssh -p 2222
$ !?tmux-view
$ ruby -v
----

=== Removendo a instalação, realizada em modo single-user, do RVM
[source,bash]
----
$ rm -rf ~/.rvm
$ sed -i '/rvm/d' ~/.bash_profile
$ sed -i '/rvm/d' ~/.bashrc
$ rm ~/.profile
$ !?kill-session
$ logout
$ !?ssh -p 2222
$ !?tmux-view
----

=== Verificando se o RVM e o Ruby foram removidos
[source,bash]
----
$ rvm list known # deverá apresentar 'command nout found'
$ ruby -v # deverá apresentar 'command nout found'
----

=== Instalando o Ruby 1.9.3, via RVM em modo multi-user
[source,bash]
----
$ curl -sSL https://get.rvm.io | sudo -E bash -s stable
$ sudo useradd -G wheel,rvm -m -s /bin/bash rvmuser
$ sudo su - rvmuser
$ type rvm | head -n 1
$ which rvm
$ rvm list known | grep 1.9
$ rvm install 1.9.3
$ ruby -v
$ logout
$ sudo gpasswd -a $USER rvm
$ !?kill-session
$ logout
----
// Esse passo é executado (nos comandos acima) após o comando logout:
// $ sudo userdel -rf rvmuser

=== Instalando o Ruby 2.1.2, via RVM em modo multi-user, e tornando-o a versão default
[source,bash]
----
$ !?ssh -p 2222
$ !?tmux-view
$ !?type
$ which rvm
$ ruby -v
$ rvm install 2.1.2
$ !-2
$ rvm list
$ rvm use 2.1.2 --default
$ !-2
$ ruby -v
----
//
//=== Removendo o Ruby 1.9.3, via RVM
//[source,bash]
//----
//$ rvm remove 1.9.3
//# Deverá dar erro pois o usuário aluno não tem privilégios para remover o diretório (criado por rvmuser)
//# Solução de contorno: fazer a remoção manual, como root:
//$ sudo rm -rf /usr/local/rvm/rubies/ruby-1.9.3-*
//$ rvm list
//----

=== Gerando um snapshot da VM
[source,bash]
----
$ sudo shutdown -h now
# aguarde a VM ser encerrada ...

$ VBoxManage snapshot vm-fedora take ruby-pos-install
----

=== Reiniciando a VM e reabrindo sua console a partir da base
[source,bash]
----
$ VBoxManage startvm vm-fedora
----
* Refaça o login pelo console da VM e execute:
[source,bash]
----
$ !?nohup ssh
$ logout
----
* Na console da base, execute:
[source,bash]
----
$ !?ssh -p 2222
$ !?tmux-view
----

== Baixando, gerando e entendendo alguns sites desenvolvidos com Awestruct & Asciidoctor

=== Instalando o Git
[source,bash]
----
$ sudo yum -y install git
----

=== Criando um túnel reverso, da VM para a base, para acesso a porta 4242
[source,bash]
----
$ sudo yum -y install autossh
$ autossh -M 0 -f -gNC \
-o "ServerAliveInterval 60" -o "ServerAliveCountMax 3" \
-R 4242:localhost:4242 $BASE_USER@base
$ ps -ef | grep autossh
----

=== Gerando (localmente) o site pessoal de Emmanuel Bernard 
* http://emmanuelbernard.com

[source,bash]
----
$ cd && mkdir -p ~/exemplos/github.com/emmanuelbernard
$ cd !$
$ git clone https://github.com/emmanuelbernard/emmanuelbernard.com
$ cd emmanuelbernard.com
$ cat > .ruby-version <<EOF
1.9.3
EOF
$ cat > .ruby-gemset <<EOF
awestruct
EOF
$ cd ..
$ cd -
$ bundle install
$ bundle exec awestruct -d
----
* Navegue pelo site gerado em http://localhost:4242.
* Dê um kbd:[Ctrl+C] no painel em que está sendo executado o servidor.

=== Gerando (localmente) o site do projeto Hibernate
* http://hibernate.org
[source,bash]
----
$ cd && mkdir -p ~/exemplos/github.com/hibernate
$ cd !$
$ git clone https://github.com/hibernate/hibernate.org
$ cd hibernate.org
$ cat > .ruby-version <<EOF
1.9.3
EOF
$ cat > .ruby-gemset <<EOF
awestruct
EOF
$ cd ..
$ cd -
$ # libs necessárias para a instalação do gem nokogiri:
$ sudo yum -y install libxml2-devel libxslt-devel
$ bundle install
$ sudo yum -y install wget
$ rake
----
* Navegue pelo site gerado em http://localhost:4242.
* Dê um kbd:[Ctrl+C] no painel em que está sendo executado o servidor.

=== Gerando (localmente) o site do projeto Ceylon
* http://ceylon.org
[source,bash]
----
$ cd && mkdir -p ~/exemplos/github.com/ceylon
$ cd !$
$ git clone https://github.com/ceylon/ceylon-lang.org
$ cd ceylon-lang.org
$ cat > .ruby-version <<EOF
1.9.3
EOF
$ cat > .ruby-gemset <<EOF
awestruct
EOF
$ cd ..
$ cd -
$ bundle install
$ rake
----
* Navegue pelo site gerado em http://localhost:4242.
* Dê um kbd:[Ctrl+C] no painel em que está sendo executado o servidor.

=== Gerando (localmente) o site do projeto WildFly
* http://wildfly.org
[source,bash]
----
$ cd && mkdir -p ~/exemplos/github.com/wildfly
$ cd !$
$ git clone https://github.com/wildfly/wildfly.org
$ cd wildfly.org
$ cat > .ruby-version <<EOF
1.9.3
EOF
$ cat > .ruby-gemset <<EOF
awestruct
EOF
$ cd ..
$ cd -
$ bundle install
$ rake
----
* Navegue pelo site gerado em http://localhost:4242.
* Dê um kbd:[Ctrl+C] no painel em que está sendo executado o servidor.

=== Gerando (localmente) o site do projeto AsciiDoctor
* http://asciidoctor.org
[source,bash]
----
$ cd && mkdir -p ~/exemplos/github.com/asciidoctor
$ cd !$
$ git clone https://github.com/asciidoctor/asciidoctor.org
$ cd asciidoctor.org
$ bundle install
$ rake
----
* Navegue pelo site gerado em http://localhost:4242.
* Dê um kbd:[Ctrl+C] no painel em que está sendo executado o servidor.

=== Gerando (localmente) o site do projeto CDI
* http://cdi-spec.org
[source,bash]
----
$ cd && mkdir -p ~/exemplos/github.com/cdi-spec
$ cd !$
$ git clone https://github.com/cdi-spec/cdi-spec.org
$ cd cdi-spec.org
$ cat > .ruby-version <<EOF
2.1.2
EOF
$ cat > .ruby-gemset <<EOF
`basename $PWD`
EOF
$ cd ..
$ cd -
$ bundle install
$ rake
----
* Navegue pelo site gerado em http://localhost:4242.
* Dê um kbd:[Ctrl+C] no painel em que está sendo executado o servidor.

=== Gerando outro snapshot da VM e reiniciando
[source,bash]
----
$ sudo shutdown -h now
# Aguarde a VM ser reiniciada ...
$ VBoxManage snapshot vm-fedora take exemplos-pos-install
$ VBoxManage startvm vm-fedora
----
* Refaça o login pelo console da VM e execute:
[source,bash]
----
$ !?nohup ssh
$ logout
----
* Na console da base, execute:
[source,bash]
----
$ !?ssh -p 2222
$ !?tmux-view
----

== Criando sites com Awestruct & Asciidoctor

=== Criando um novo site com o Awestruct
==== Instalando o Awestruct
[source,bash]
----
$ rvm use 2.1.2@$PROJECT --create
$ gem install tilt --version 1.4.1
$ gem install awestruct --version 0.5.4.rc3
$ gem install asciidoctor
----

==== Criando um novo projeto
[source,bash]
----
$ mkdir -p $PROJECT
$ cd !$
$ rvm use 2.1.2@$PROJECT
$ awestruct -i -f foundation
----

==== Configurando um Gemfile
[source,bash]
----
$ cat > Gemfile << LINES
source 'https://rubygems.org'
gem 'awestruct', '0.5.4.rc3'
gem 'asciidoctor', '0.1.4'
gem 'tilt', '1.4.1'
gem 'rake', '>= 0.9.2'
gem 'git', '1.2.6'
LINES
----

==== Fazendo o lock das dependências
[source,bash]
----
$ gem install bundler
$ bundle install
----

==== Vendo a estrutura do projeto
[source,bash]
----
$ tree | less
----

==== Gerando o site
[source,bash]
----
$ rake
----

=== Acessando o site gerado na VM a partir da máquina base

* Abra seu browser na máquina base no endereço http://localhost:4242

==== Observando a estrutura do site gerado
[source,bash]
----
$ tree _site/ | less
----

=== Iniciando o uso do Git para o controle de versões do site

==== Configurando o Git com tuas informações
[source,bash]
----
$ git config --global user.email "$GITHUB_EMAIL"
$ git config --global user.name "$GITHUB_NAME"
$ cat ~/.gitconfig
----

==== Configurando um repositório Git para o projeto
[source,bash]
----
$ git init .
----

==== Instruindo o Git a ignorar arquivos gerados
[source,bash]
----
$ cat > .gitignore << LINES
/.awestruct/
/.ruby-*
/.sass-cache/
/_site/
/_tmp/
/Gemfile.lock
LINES
----

==== Informando que o site não será gerado via Jekyll
[source,bash]
----
$ touch .nojekyll
----

==== Adicionando os arquivos não ignorados e fazendo o primeiro commit
[source,bash]
----
$ git add .
$ git commit -m 'commit inicial'
----

=== Enviando o site para o GitHub

==== Criando um repositório remoto no GitHub
* Abra o site do GitHub e crei um repositório nomeado 'join-community' em tua conta.
* Informe na descrição: 'Execução do tutorial de AweStruct ministrado por Paulo Jerônimo no Join Community 2014'.

==== Publicando seu repositório local no GitHub
[source,bash]
----
$ git remote add origin https://github.com/$GITHUB_USER/$PROJECT
$ git push origin master
----

==== Configurando a identidade do site
[source,bash]
----
$ cat > _config/site.yml <<EOF
name: $PROJECT_NAME
title: $PROJECT_TITLE
org: $GITHUB_NAME
author: $GITHUB_USER
author_url: https://github.com/$GITHUB_USER
base_url: ''
ctx_path: ''
EOF
$ cat _config/site.yml
----

==== Adicionando configurações para configurar o processador
[source,bash]
----
$ cat >> _config/site.yml <<EOF
interpolate: false
haml:
  :ugly: true
EOF
----

==== Limpando e regerando o site para ver as mudanças
* Dê um kbd:[Ctrl+C] no painel em que está sendo executado o rake e reinicie-o:
[source,bash]
----
$ rake clean preview
----
* Recarregue http://localhost:4242/ e observe as mudanças;

==== Configurando o uso do AsciiDoctor
[source,bash]
----
$ cat >> _config/site.yml <<EOF
asciidoctor:
  :safe: safe
  :attributes:
    sitename: $PROJECT_NAME
    base_url: ''
    ctx_path: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font
EOF
----

==== Criando a página about.adoc na pasta do projeto
[source,bash]
----
$ cat > about.adoc <<EOF
= About http://joincommunity.com.br[{sitename}]
$GITHUB_USER
:page-layout: base
:showtitle:

[.lead]
{sitename} is a cool event in http://j.mp/cade-goiania[Goiânia/GO/Brasil]!
This site was founded by {author} and build by the execution of a 
https://github.com/paulojeronimo/join-community-2014/blob/master/passo-a-passo.adoc[step by step guide] 
created by http://paulojeronimo.info[Paulo Jerônimo].
It's quickly becoming much bigger than this humble beginning.

This page is written in http://asciidoc.org[AsciiDoc].
It's transformed by http://awestruct.org[Awestruct] and http://asciidoctor.org[Asciidoctor] 
into a webpage for this static website.
EOF
----

==== Adicionando um link para a página about na barra de navegação
[source,bash]
----
$ sed -i '31 i \
        %li.divider\
          %li\
            %a(href="#{site.ctx_path}/about.html") About\
' _layouts/base.html.haml
----

==== Adicionando o estilo referenciando no documento (.lead)
* Um pouco de http://tableless.com.br/sass-um-outro-metodo-de-escrever-css/[Sass]:
[source,bash]
----
$ sed -i '$ a \
.paragraph.lead > p {\
  @extend %lead;\
}\
' stylesheets/app.scss
----
* Recarregue http://localhost:4242 e observe as mudanças;
* Pressione kbd:[Ctrl+C] no console do servidor;
* Reinicie o servidor executando
[source,bash]
----
$ rake
----
* Acesse o link http://localhost:4242/about.html[About] (canto lateral esquerdo).
* Pressione kbd:[Ctrl+C] no console do servidor;

==== Observando as mudanças que precisam ser confirmadas e fazendo o commit
[source,bash]
----
$ git status
$ git add .
$ git commit -m "novas funcionalidades"
$ git push origin master
----

==== Criando o ramo de publicação (gh-pages)
[source,bash]
----
$ git checkout --orphan gh-pages
$ rm -rf *
$ rm -rf .awestruct* .sass-* .gitignore .gitmodules
$ git rm --cached *
$ echo "GitHub Pages placeholder" > index.html
$ git add index.html .nojekyll
$ git commit -m "iniciando o ramo de publicação para o GitHub Pages"
----

==== Implantando o ramo de publicação
[source,bash]
----
$ git push origin gh-pages
----

==== Visualizando o seu site 
* Acesse (substituindo as variáveis pelos seus valores, obviamente): http://$GITHUB_USER.github.io/$PROJECT
[NOTE]
------
O GitHub Pages pode demorar até 10 minutos para fazer a primeira disponiblização do site.
------

==== Retornando para o ramo master
[source,bash]
----
$ git checkout master
----

==== Configurando o implantador do Awestruct para publicar o site no GitHub Pages
[source,bash]
----
$ cat >> _config/site.yml <<EOF
profiles:
  development:
    deploy: nil
  production:
    base_url: http://$GITHUB_USER.github.io/$PROJECT
    ctx_path: /$PROJECT
    asciidoctor:
      :attributes:
        base_url: http://$GITHUB_USER.github.io/$PROJECT
        ctx_path: /$PROJECT
        imagesdir: http://$GITHUB_USER.github.io/$PROJECT/images
    deploy:
      host: github_pages
      branch: gh-pages
EOF
----

==== Fazendo o commit da configuração
[source,bash]
----
$ git commit _config/site.yml -m "adicionado o profile para implantação no GitHub Pages"
$ git push origin master
----

==== Implantando no GitHub Pages
[source,bash]
----
$ rake clean deploy
----
* Recarregue http://$GITHUB_USER.github.io/$PROJECT
=======
