= Criação e disponibilização de uma máquina virtual (VM) mínima com o Fedora 20
:author: Paulo Jerônimo
:email: pj@paulojeronimo.info
:toc:
:numbered:

== Preparando um Fedora para criar e disponibilizar uma VM Fedora
=== Instalando alguns utilitários
[source,bash]
----
$ sudo yum -y install \
vim-enhanced \
p7zip
----

=== Instalando o Apache
* Instale, inicie e disponibilize a execução do Apache na inicialização da máquina:
[source,bash]
----
$ sudo yum -y install httpd
$ sudo systemctl start httpd
$ sudo systemctl enable httpd
----
* Configure o firewall para possibilitar o acesso ao Apache:
[source,bash]
----
$ sudo firewall-cmd --permanent --add-service=http
----
* Execute o comando a seguir observando sua saída. Ela apresenta algumas linhas relevantes da configuração atual:
[source,bash]
----
$ sed -n '11,25p;31,35p' /etc/httpd/conf.d/userdir.conf
----
* Edite o arquivo a seguir, conforme a execução do sed e, em seguida, reexecute o comando anterior para conferir as alterações:
[source,bash]
----
$ sudo sed -i '
s/\(. *UserDir\) disabled/\1 public_html/g
s/SymLinksIfOwnerMatch/FollowSymLinks/g
' /etc/httpd/conf.d/userdir.conf
----
* Recarregue as configurações do Apache:
[source,bash]
----
$ sudo systemctl reload httpd
----
* Ajuste e testes as permissões para o diretório $HOME, conforme a seguir:
[source,bash]
----
$ sudo chmod 755 $HOME
$ ls -ld $HOME
----
* Faça os ajustes necessários no SELinux:
[source,bash]
----
$ sudo setsebool -P httpd_read_user_content 1
$ sudo setsebool -P httpd_enable_homedirs 1
----
* Crie a pasta public_html e um arquivo index.html para validar o acesso via HTTP:
[source,bash]
----
$ mkdir -p ~/public_html
$ echo "Teste do $USER" > !$/index.html
----
* Abra o browser em http://localhost/~pj/ para verificar o acesso a página index.html; 

=== Instalando o VirtualBox (versão 4.3.12)
* Instale o repositório do VirtualBox para o Fedora, conforme a seguir:
[source,bash]
----
$ sudo curl http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo -o /etc/yum.repos.d/virtualbox.repo
----
* Instale os pacotes que serão utilizados na instalação do VirtualBox:
[source,bash]
----
$ sudo yum -y group install c-development
$ sudo yum -y install kernel-devel
----
* Instale o VirtualBox:
[source,bash]
----
$ sudo yum -y install VirtualBox-4.3
----
* Verifique se foi criado o grupo vboxusers
[source,bash]
----
$ grep vboxusers /etc/group
----
* Adicione seu usuário ao grupo vbox users e reexecute o comando anterior:
[source,bash]
----
$ sudo gpasswd -a $USER vboxusers
$ grep vboxusers /etc/group
----
* Execute o passo a seguir SE tiver ocorrido algum erro durante a instalação do VirtualBox OU se o kernel do Linux tiver sido atualizado:
[source,bash]
----
$ sudo /etc/init.d/vboxdrv setup
----
* Faça o logout de seu usuário:
[source,bash]
----
$ gnome-session-quit
----
* Instale o VirtualBox Extension Pack:
[source,bash]
----
$ VER=4.3.12
$ VEP=Oracle_VM_VirtualBox_Extension_Pack-$VER.vbox-extpack
$ wget -c http://download.virtualbox.org/virtualbox/$VER/$VEP
$ VBoxManage extpack install $VEP
----
* Logue-se novamente e inicie o VirtualBox:
[source,bash]
----
$ VirtualBox
----

== Criando a VM
=== Configurando variáveis de ambiente
[source,bash]
----
$ f=~/join-community-2014.conf; cat > $f <<'EOF'
# diretório dos mirrors
MIRRORS_DIR=/data/mirrors

# diretório do mirror do Fedora
FEDORA_MIRROR=$MIRRORS_DIR/Fedora-20-x86_64

# diretório de download de arquivos desse passo a passo
DOWNLOADS_DIR=~/join-community-2014.downloads

# diretório de configurações do Apache
APACHE_CONF_DIR=/etc/httpd/conf.d

# comando para fazer o reload das configurações do Apache
APACHE_RELOAD_CMD="systemctl reload httpd"

# localização do ISO de instalação do Fedora
export FEDORA_ISO=$FEDORA_MIRROR/releases/20/Fedora/x86_64/iso/Fedora-20-x86_64-netinst.iso
EOF
$ vim $f
$ grep `basename $f` ~/.bashrc &> /dev/null || \
echo "[ -f $f ] && source $f"  >> ~/.bashrc
$ source $f
----

=== Configurando o uso de um mirror local do Fedora
[source,bash]
----
$ mkdir -p $DOWNLOADS_DIR
$ cd !$
$ git clone http://github.com/paulojeronimo/mirrors.git
$ cd mirrors
$ cat > .bin/config <<EOF
LOCAL_MIRRORS_DIR_ON_LINUX=$MIRRORS_DIR
EOF
$ .bin/create-links
----

=== Criando e/ou atualizando o mirror local
[source,bash]
----
$ Fedora/20/x86_64/mirror.sh
----

=== Configurando o Apache
[source,bash]
----
$ cd $DOWNLOADS_DIR
$ git clone https://github.com/paulojeronimo/join-community-2014.git
$ ./join-community-2014/configurar-apache.sh
----

=== Criando, iniciando e instalando o Fedora na VM
[source,bash]
----
$ ./mirrors/Fedora/20/x86_64/vm/vbox
$ VBoxManage startvm vm-fedora
----
[NOTE]
======
No boot da VM, pressione <Tab> e adicione +ks=http://10.0.2.2/ks+ ao final da linha de comando.
======

=== Entendo o processo de instalação automática do Fedora
[source,bash]
----
$ vim join-community-2014/vm/ks
----

=== Fazendo o shutdown após a instalação e removendo o "DVD" do Fedora do drive
[source,bash]
----
$ VBoxManage controlvm vm-fedora acpipowerbutton
$ VBoxManage storageattach vm-fedora \
--storagectl "IDE Controller" \
--port 1 --device 0 --type dvddrive --medium emptydrive
----

=== Reiniciando a VM e removendo arquivos desnecessários
[source,bash]
----
$ VBoxManage startvm vm-fedora
----

* Logue-se na VM (usuário/senha: aluno/@lun00123) e execute:
[source,bash]
----
$ sudo package-cleanup -y --oldkernels --count=1
$ d=/var/cache/yum/; sudo bash -c "rm -rf $d; mkdir -p $d"
$ history -c
----

=== Desligando e reconfigurando os drives de CD/DVD da VM
[source,bash]
----
$ VBoxManage controlvm vm-fedora acpipowerbutton
$ VBoxManage storagectl vm-fedora \ 
--name "IDE Controller" --remove
$ VBoxManage storagectl vm-fedora \
--name "IDE Controller" --add ide --controller PIIX4
$ VBoxManage storageattach vm-fedora \
--storagectl "IDE Controller" \
--port 1 --device 0 --type dvddrive --medium emptydrive
----

=== Desregistrando a VM
[source,bash]
----
$ VBoxManage unregistervm vm-fedora
----

== Disponibilizando a VM para download
=== Limpando arquivos desnecessários e compactando a VM
[source,bash]
----
$ cd ~/VirtualBox\ VMs
$ (cd vm-fedora && \
find . ! \( -name . -o -name vm-fedora.vbox -o -name vm-fedora.vdi \) | \
xargs rm -rf)
$ 7za a -mmt -v200m vm-fedora vm-fedora/
$ sha1sum vm-fedora.7z.* > vm-fedora.sha1sum
----
=== Gerando o script para o download da VM
[source,bash]
----
$ f=vm-fedora.download.sh; sed "s/COUNT/`ls vm-fedora.7z.* | wc -l`/g" \
$DOWNLOADS_DIR/join-community-2014/vm/$f > $f
----

=== Instalando um cliente para o Google Drive
[source,bash]
----
$ sudo yum install ocaml ocaml-camlp4-devel ocaml-ocamldoc
$ mkdir ~/Projects/github.com/OCamlPro
$ cd !$
$ git clone https://github.com/OCamlPro/opam.git
$ cd opam
$ ./configure
$ make
$ sudo make install
$ sudo yum install m4 fuse fuse-devel libcurl-devel libsqlite3x-devel zlib-devel
$ opam init
$ opam update
$ opam install google-drive-ocamlfuse
$ ~/.opam/system/bin/google-drive-ocamlfuse
$ export PATH=~/.opam/system/bin:$PATH
----

=== Fazendo upload para o Google Drive
* Montando o Google Drive:
[source,bash]
----
$ mkdir -p ~/google-drive
$ google-drive-ocamlfuse ~/google-drive
----
* Fazendo a atualização da VM:
[source,bash]
----
$ rm -rf ~/google-drive/vm-fedora/*
$ rsync -av --progress vm-fedora.* ~/google-drive/vm-fedora/
----
* Desmontando o Google Drive:
[source,bash]
-----
$ fusermount -u ~/google-drive
-----
* Terminado o upload, os arquivos ficam disponíveis em http://gdriv.es/vm-fedora/. Essa é uma URL curta, que criei no http://gdriv.es, para a URL longa https://drive.google.com/folderview?id=0B_tTlCk55SmjZGlNckhCRldUUDQ.

== Para reiniciar a criação da VM
[source,bash]
----
$ sudo rm -rf /etc/httpd/conf.d/join-community-2014.conf 
$ sudo systemctl reload httpd
$ rm -rf join-community-2014.*
$ VBoxManage unregistervm vm-fedora --delete
$ rm -rf ~/VirtualBox\ VMs/vm-fedora.7z.*
$ sed -i '/join-community/d' ~/.bashrc
$ exit
----
